//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "job_run_diffs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub job_run_id: i32,
    pub diff_type: String,
    pub entity_key: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub old_value: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub new_value: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::job_runs::Entity",
        from = "Column::JobRunId",
        to = "super::job_runs::Column::Id"
    )]
    JobRuns,
}

impl Related<super::job_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JobRuns.def()
    }
}
