//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "organizations")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub pid: Uuid,
    pub name: String,
    #[sea_orm(unique)]
    pub slug: String,
    pub is_personal: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::org_members::Entity")]
    OrgMembers,
    #[sea_orm(has_many = "super::org_invites::Entity")]
    OrgInvites,
}

impl Related<super::org_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrgMembers.def()
    }
}

impl Related<super::org_invites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OrgInvites.def()
    }
}
