#!/bin/sh
set -e

# Generate .env.prod with random secrets for production deployment.
#
# Usage:
#   ./dev/gen-env.sh example.com auth.example.com > .env.prod
#
# Then fill in the OIDC and SMTP placeholders manually,
# or run ./dev/setup-oidc.sh to auto-provision OIDC values.

if [ $# -lt 2 ]; then
    echo "Usage: $0 <app-domain> <auth-domain>" >&2
    echo "Example: $0 example.com auth.example.com > .env.prod" >&2
    exit 1
fi

APP_DOMAIN="$1"
AUTH_DOMAIN="$2"

# Generate a random hex string of N bytes (output is 2*N hex chars)
rand_hex() {
    head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'
}

# Generate a random base64 string (URL-safe, no padding)
rand_b64() {
    head -c "$1" /dev/urandom | base64 | tr '+/' '-_' | tr -d '='
}

cat <<EOF
# ── Production Environment ────────────────────────────────────────
# Generated by dev/gen-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Domain: ${APP_DOMAIN} | Auth: ${AUTH_DOMAIN}
#
# KEEP THIS FILE SECRET. Do not commit to version control.

# ── Domains & Ports ───────────────────────────────────────────────
APP_DOMAIN=${APP_DOMAIN}
AUTH_DOMAIN=${AUTH_DOMAIN}
APP_PORT=5150
ZITADEL_PORT=8081

# ── App Database (PostgreSQL) ─────────────────────────────────────
APP_DB_PASSWORD=$(rand_hex 32)

# ── Zitadel Database (PostgreSQL) ─────────────────────────────────
ZITADEL_DB_POSTGRES_PASSWORD=$(rand_hex 32)
ZITADEL_DB_ZITADEL_PASSWORD=$(rand_hex 32)

# ── Zitadel Masterkey (exactly 32 characters) ────────────────────
ZITADEL_MASTERKEY=$(rand_b64 24 | head -c 32)

# ── JWT ───────────────────────────────────────────────────────────
JWT_SECRET=$(rand_b64 48)

# ── OIDC (filled by dev/setup-oidc.sh or manually) ───────────────
OIDC_CLIENT_ID=CHANGE_ME
OIDC_CLIENT_SECRET=CHANGE_ME
OIDC_PROJECT_ID=CHANGE_ME

# ── SMTP (for Zitadel outbound emails) ───────────────────────────
SMTP_HOST=CHANGE_ME
SMTP_PORT=587
SMTP_USER=CHANGE_ME
SMTP_PASSWORD=CHANGE_ME

# ── Mailer (for app outbound emails) ─────────────────────────────
MAILER_HOST=CHANGE_ME
MAILER_PORT=587
MAILER_USER=CHANGE_ME
MAILER_PASSWORD=CHANGE_ME
EOF
