#!/bin/sh
set -e

# One-time Zitadel OIDC bootstrap for production.
#
# Prerequisites:
#   1. .env.prod exists (generated by dev/gen-env.sh)
#   2. Zitadel is running (podman compose -f compose.prod.yaml up -d zitadel)
#
# This script:
#   - Waits for Zitadel to become healthy
#   - Extracts the machine-user PAT from compose logs
#   - Creates a project + OIDC app via the Zitadel Management API
#   - Writes OIDC_CLIENT_ID, OIDC_CLIENT_SECRET, OIDC_PROJECT_ID back to .env.prod

ENV_FILE=".env.prod"
COMPOSE="podman compose -f compose.prod.yaml"

if [ ! -f "$ENV_FILE" ]; then
    echo "ERROR: $ENV_FILE not found. Run dev/gen-env.sh first." >&2
    exit 1
fi

# shellcheck disable=SC1090
. "$ENV_FILE"

ZITADEL_API="http://localhost:${ZITADEL_PORT:-8081}"
APP_DOMAIN="${APP_DOMAIN:?APP_DOMAIN must be set in $ENV_FILE}"

echo "==> Waiting for Zitadel at ${ZITADEL_API}..."
RETRIES=0
MAX_RETRIES=60
until curl -sf "${ZITADEL_API}/debug/ready" >/dev/null 2>&1; do
    RETRIES=$((RETRIES + 1))
    if [ "$RETRIES" -ge "$MAX_RETRIES" ]; then
        echo "ERROR: Zitadel did not become ready after ${MAX_RETRIES} attempts." >&2
        exit 1
    fi
    printf "."
    sleep 2
done
echo " ready."

echo "==> Extracting PAT from Zitadel logs..."
PAT=$($COMPOSE logs zitadel 2>&1 | grep -oE '^[A-Za-z0-9_-]{30,}' | head -1 | tr -d '[:space:]')
if [ -z "$PAT" ]; then
    echo "ERROR: Could not extract PAT from Zitadel logs." >&2
    echo "  Make sure Zitadel started with FIRSTINSTANCE machine user config." >&2
    exit 1
fi
echo "  PAT: ${PAT:0:8}...${PAT: -4} (truncated)"

AUTH="Authorization: Bearer ${PAT}"

echo "==> Creating OIDC project..."
PROJECT_RESP=$(curl -sf -X POST "${ZITADEL_API}/management/v1/projects" \
    -H "$AUTH" \
    -H "Content-Type: application/json" \
    -d "{\"name\": \"fracture-cms\", \"projectRoleAssertion\": true}")

PROJECT_ID=$(echo "$PROJECT_RESP" | sed -n 's/.*"id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
if [ -z "$PROJECT_ID" ]; then
    echo "ERROR: Failed to create project. Response:" >&2
    echo "$PROJECT_RESP" >&2
    exit 1
fi
echo "  Project ID: ${PROJECT_ID}"

echo "==> Creating OIDC application..."
APP_RESP=$(curl -sf -X POST "${ZITADEL_API}/management/v1/projects/${PROJECT_ID}/apps/oidc" \
    -H "$AUTH" \
    -H "Content-Type: application/json" \
    -d "{
        \"name\": \"fracture-cms-web\",
        \"redirectUris\": [\"https://${APP_DOMAIN}/api/auth/oidc/callback\"],
        \"postLogoutRedirectUris\": [\"https://${APP_DOMAIN}\"],
        \"responseTypes\": [\"OIDC_RESPONSE_TYPE_CODE\"],
        \"grantTypes\": [\"OIDC_GRANT_TYPE_AUTHORIZATION_CODE\"],
        \"appType\": \"OIDC_APP_TYPE_WEB\",
        \"authMethodType\": \"OIDC_AUTH_METHOD_TYPE_BASIC\"
    }")

CLIENT_ID=$(echo "$APP_RESP" | sed -n 's/.*"clientId"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)
CLIENT_SECRET=$(echo "$APP_RESP" | sed -n 's/.*"clientSecret"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)

if [ -z "$CLIENT_ID" ] || [ -z "$CLIENT_SECRET" ]; then
    echo "ERROR: Failed to create OIDC app. Response:" >&2
    echo "$APP_RESP" >&2
    exit 1
fi
echo "  Client ID: ${CLIENT_ID}"

echo "==> Writing OIDC values to ${ENV_FILE}..."
sed -i "s|^OIDC_CLIENT_ID=.*|OIDC_CLIENT_ID=${CLIENT_ID}|" "$ENV_FILE"
sed -i "s|^OIDC_CLIENT_SECRET=.*|OIDC_CLIENT_SECRET=${CLIENT_SECRET}|" "$ENV_FILE"
sed -i "s|^OIDC_PROJECT_ID=.*|OIDC_PROJECT_ID=${PROJECT_ID}|" "$ENV_FILE"

echo ""
echo "==> OIDC bootstrap complete!"
echo "    Client ID:     ${CLIENT_ID}"
echo "    Project ID:    ${PROJECT_ID}"
echo "    Secret written to ${ENV_FILE}"
echo ""
echo "Next steps:"
echo "  1. Review ${ENV_FILE}"
echo "  2. Restart the app: ${COMPOSE} up -d app"
