use base64::{engine::general_purpose::STANDARD as BASE64, Engine as _};
use clap::{Parser, Subcommand};
use rand::Rng;
use std::process::Command;

#[derive(Parser)]
#[command(name = "fracture-ctl", about = "Fracture CMS project management")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Generate a secure configuration file
    Init {
        /// Generate production config (default: development)
        #[arg(long)]
        prod: bool,
    },
    /// Run all CI checks (fmt, clippy, semgrep, tests)
    Ci,
    /// Start the development environment
    Dev {
        /// Run setup (Zitadel OIDC provisioning) before starting
        #[arg(long)]
        setup: bool,
    },
    /// Stop all services
    Down {
        /// Use production compose
        #[arg(long)]
        prod: bool,
    },
}

fn generate_secret(bytes: usize) -> String {
    let mut buf = vec![0u8; bytes];
    rand::rng().fill(&mut buf[..]);
    BASE64.encode(&buf)
}

fn cmd_init(prod: bool) {
    let jwt_secret = generate_secret(32);

    if prod {
        let db_password = generate_secret(24);
        println!(
            r#"# Fracture CMS — Production configuration
# Generated by fracture-ctl init --prod

JWT_SECRET={jwt_secret}

# Database — SQLite is the default. Uncomment for PostgreSQL:
# APP_DB_PASSWORD={db_password}
# DATABASE_URL=postgres://fracture:${{APP_DB_PASSWORD}}@db:5432/fracture

# OIDC — optional. The app serves pages without it; login returns 503.
# Configure your identity provider (Zitadel, Keycloak, Auth0, etc.):
# OIDC_ISSUER_URL=https://auth.example.com
# OIDC_CLIENT_ID=
# OIDC_CLIENT_SECRET=
# OIDC_REDIRECT_URI=https://example.com/api/auth/oidc/callback
# OIDC_POST_LOGOUT_REDIRECT_URI=https://example.com

# SMTP — optional. Invite emails fail silently if not configured.
# MAILER_HOST=smtp.example.com
# MAILER_PORT=587
# MAILER_USER=
# MAILER_PASSWORD="#
        );
    } else {
        println!(
            r#"# Fracture CMS — Development configuration
# Generated by fracture-ctl init
# OIDC values are filled by ./dev/setup.sh after Zitadel starts.

JWT_SECRET={jwt_secret}
OIDC_PROJECT_ID=
OIDC_CLIENT_ID=
OIDC_CLIENT_SECRET="#
        );
    }
}

fn cmd_ci() {
    let ci_script = find_script("dev/ci.sh");
    if ci_script.is_empty() {
        eprintln!("Error: dev/ci.sh not found");
        std::process::exit(1);
    }
    let status = Command::new("bash")
        .arg(&ci_script)
        .status()
        .expect("failed to run ci.sh");
    std::process::exit(status.code().unwrap_or(1));
}

fn cmd_dev(setup: bool) {
    let compose = find_compose();
    if setup {
        let setup_script = find_script("dev/setup.sh");
        if setup_script.is_empty() {
            eprintln!("Error: dev/setup.sh not found");
            std::process::exit(1);
        }
        let status = Command::new("bash")
            .arg(&setup_script)
            .status()
            .expect("failed to run setup.sh");
        if !status.success() {
            eprintln!("Setup failed");
            std::process::exit(1);
        }
    }

    // Start mailcrab + app (Zitadel started by setup or already running)
    let status = Command::new("podman")
        .args(["compose", "-f", &compose, "up", "-d", "mailcrab", "app"])
        .status()
        .expect("failed to run podman compose");

    if status.success() {
        println!("\nDevelopment environment running:");
        println!("  App:     http://localhost:5150");
        println!("  Zitadel: http://localhost:8080");
        println!("  Mail:    http://localhost:1080");
    }
    std::process::exit(status.code().unwrap_or(1));
}

fn cmd_down(prod: bool) {
    let compose = if prod {
        "compose.prod.yaml".to_string()
    } else {
        find_compose()
    };
    let status = Command::new("podman")
        .args(["compose", "-f", &compose, "down"])
        .status()
        .expect("failed to run podman compose down");
    std::process::exit(status.code().unwrap_or(1));
}

fn find_compose() -> String {
    if std::path::Path::new("compose.yaml").exists() {
        "compose.yaml".to_string()
    } else if std::path::Path::new("docker-compose.yaml").exists() {
        "docker-compose.yaml".to_string()
    } else {
        eprintln!("Error: no compose.yaml found");
        std::process::exit(1);
    }
}

fn find_script(name: &str) -> String {
    if std::path::Path::new(name).exists() {
        name.to_string()
    } else {
        String::new()
    }
}

fn main() {
    let cli = Cli::parse();
    match cli.command {
        Commands::Init { prod } => cmd_init(prod),
        Commands::Ci => cmd_ci(),
        Commands::Dev { setup } => cmd_dev(setup),
        Commands::Down { prod } => cmd_down(prod),
    }
}
