name: Release
on:
  push:
    tags: ['v*']

permissions:
  contents: read
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yaml

  release:
    needs: ci
    uses: ./.github/workflows/release-app.yaml
    with:
      image_name: ghcr.io/${{ github.repository }}
    secrets: inherit
